### ISSUE TITLE
Can't make it work on my Linux box

### ISSUE THREAD

**Issue by martinschayna** [DevVlad/abra-first-assignment#1]
I have no idea what's wrong, it looks like there is something in the Babel config :disappointed: 
But keep calm, it'll wait till Monday.

```
$ npm install
...
$ npm start
...
ERROR in ./app/main.jsx
Module build failed: SyntaxError: /home/mase/Workspace/abra-first-assignment/app/main.jsx: Unexpected token (6:2)
  4 | 
  5 | ReactDOM.render(
> 6 |   <App />,
    |   ^
  7 |   document.body.appendChild(document.createElement('div'))
  8 | );
  9 | 
    at Parser.pp.raise (/home/mase/Workspace/abra-first-assignment/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/home/mase/Workspace/abra-first-assignment/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.parseExprAtom (/home/mase/Workspace/abra-first-assignment/node_modules/babylon/lib/parser/expression.js:517:12)
...
```

**Comment by DevVlad** [comment]
Solved....
